backend:
  name: git-gateway
  branch: main # Hoặc nhánh chính của bạn

media_folder: "/IMG/" # Đường dẫn lưu trữ hình ảnh
public_folder: "/IMG/"

collections:
  - name: "blog"
    label: "Blog"
    folder: "index.html"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Summary", name: "summary", widget: "text", required: false }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Featured Image", name: "thumbnail", widget: "image", required: false }
      - { label: "Author", name: "author", widget: "string", required: false }
      - { label: "Category", name: "category", widget: "select", options: ["Gameplay", "Characters", "Events", "Guides"], required: false }

